# Generated by Django 6.0.2 on 2026-02-06 02:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roulette_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AwardList',
            fields=[
                ('activity_name', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('config', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activities', to='roulette_app.rouletteconfig')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AwardHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.CharField(max_length=100)),
                ('prize_name', models.CharField(max_length=100)),
                ('drawn_at', models.DateTimeField()),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='histories', to='roulette_app.awardlist')),
            ],
            options={
                'ordering': ['-drawn_at'],
            },
        ),
    ]
